global:
  scrape_interval:     10s # Prometheus will scrape our spring boot applications every 10 seconds
  evaluation_interval: 10s # Evaluate internal custom rules in prometheus every 10 seconds

scrape_configs:
  - job_name: 'product_service'
    metrics_path: '/actuator/prometheus' # The endpoint which prometheus will scrape
    static_configs:
      - targets: ['product-service:8080'] # The spring boot application name and port
        labels:
          application: 'Product Service Application' # The application name
  - job_name: 'order_service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['order-service:8080']
        labels:
          application: 'Order Service Application'
  - job_name: 'inventory_service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['inventory-service:8080']
        labels:
          application: 'Inventory Service Application'
  - job_name: 'notification_service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['notification-service:8080']
        labels:
          application: 'Notification Service Application'